/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sangraj.scrap.ScrapUI;

import com.sangraj.scrap.ui.process.GrabberProcess;
import com.sangraj.scrap.ui.process.ImageSaveProcess;
import com.sangraj.scrap.ui.process.MatcherProcess;
import com.sangraj.scrap.ui.process.MatcherSaveProcess;
import com.sangraj.scrap.ui.process.ScrapProcess;
import com.sangraj.scrap.ui.process.ScrapSaveProcess;

//TEXT AREAS ARE txtScrap,txtMatch and txtBrowser;
//TEXT FIELDS ARE txtURL,txtMatcher/(2,3),txtRegEx,txtImage
/**
 *
 * @author Song Grudge Ranjit
 */
public class ScrapUI extends javax.swing.JFrame {

    /**
     * Creates new form ScrapUI
     */
    public ScrapUI() {
        setTitle("Scrapping.......");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtBrowser = new javax.swing.JTextArea();
        txtRegEx = new javax.swing.JTextField();
        btnScrap = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtScrap = new javax.swing.JTextArea();
        txtMatcher3 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtMatch = new javax.swing.JTextArea();
        btnMatcher = new javax.swing.JButton();
        btnSave1 = new javax.swing.JButton();
        txtMatcher = new javax.swing.JTextField();
        txtMatcher2 = new javax.swing.JTextField();
        btnImage = new javax.swing.JButton();
        txtImage = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnClearM = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtURL = new javax.swing.JTextField();
        btnGo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        txtBrowser.setEditable(false);
        txtBrowser.setBackground(new java.awt.Color(0, 0, 0));
        txtBrowser.setColumns(20);
        txtBrowser.setForeground(new java.awt.Color(0, 153, 51));
        txtBrowser.setRows(5);
        txtBrowser.setSelectedTextColor(new java.awt.Color(0, 255, 0));
        txtBrowser.setSelectionColor(new java.awt.Color(153, 255, 51));
        jScrollPane1.setViewportView(txtBrowser);

        txtRegEx.setBackground(new java.awt.Color(0, 0, 0));
        txtRegEx.setForeground(new java.awt.Color(255, 255, 255));

        btnScrap.setBackground(new java.awt.Color(255, 0, 0));
        btnScrap.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        btnScrap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sangraj/scrap/resources/Doc-Scrap-icon.png"))); // NOI18N
        btnScrap.setText("SCRAP");
        btnScrap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scrapButtonClick(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(0, 0, 0));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sangraj/scrap/resources/Save.png"))); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonClick(evt);
            }
        });

        txtScrap.setEditable(false);
        txtScrap.setBackground(new java.awt.Color(0, 0, 0));
        txtScrap.setColumns(20);
        txtScrap.setForeground(new java.awt.Color(0, 102, 51));
        txtScrap.setRows(5);
        jScrollPane2.setViewportView(txtScrap);

        txtMatcher3.setBackground(new java.awt.Color(0, 0, 0));
        txtMatcher3.setForeground(new java.awt.Color(255, 255, 255));

        txtMatch.setEditable(false);
        txtMatch.setBackground(new java.awt.Color(0, 0, 0));
        txtMatch.setColumns(20);
        txtMatch.setForeground(new java.awt.Color(0, 153, 51));
        txtMatch.setRows(5);
        jScrollPane3.setViewportView(txtMatch);

        btnMatcher.setBackground(new java.awt.Color(255, 0, 0));
        btnMatcher.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        btnMatcher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sangraj/scrap/resources/match.png"))); // NOI18N
        btnMatcher.setText("SELECT");
        btnMatcher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matcherClick(evt);
            }
        });

        btnSave1.setBackground(new java.awt.Color(0, 0, 0));
        btnSave1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sangraj/scrap/resources/Save.png"))); // NOI18N
        btnSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matcherSaveClick(evt);
            }
        });

        txtMatcher.setBackground(new java.awt.Color(0, 0, 0));
        txtMatcher.setForeground(new java.awt.Color(255, 255, 255));

        txtMatcher2.setBackground(new java.awt.Color(0, 0, 0));
        txtMatcher2.setForeground(new java.awt.Color(255, 255, 255));

        btnImage.setBackground(new java.awt.Color(0, 0, 0));
        btnImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sangraj/scrap/resources/Pictures-icon.png"))); // NOI18N
        btnImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImageButtonClick(evt);
            }
        });

        txtImage.setBackground(new java.awt.Color(0, 0, 0));
        txtImage.setForeground(new java.awt.Color(255, 255, 255));

        btnClear.setBackground(new java.awt.Color(0, 0, 0));
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sangraj/scrap/resources/clear.png"))); // NOI18N
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonClick(evt);
            }
        });

        btnClearM.setBackground(new java.awt.Color(0, 0, 0));
        btnClearM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sangraj/scrap/resources/clear.png"))); // NOI18N
        btnClearM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matchFieldClearClick(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(txtRegEx, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnScrap)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(txtMatcher, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMatcher2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMatcher3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMatcher)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnClearM, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtImage, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnImage, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3))))
                .addGap(13, 13, 13))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMatcher, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMatcher2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMatcher3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMatcher, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(txtImage)
                    .addComponent(btnClearM, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnScrap, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtRegEx))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sangraj/scrap/resources/Internet-url-icon.png"))); // NOI18N

        txtURL.setBackground(new java.awt.Color(0, 0, 0));
        txtURL.setForeground(new java.awt.Color(255, 255, 255));

        btnGo.setBackground(new java.awt.Color(255, 0, 0));
        btnGo.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        btnGo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sangraj/scrap/resources/Search-icon.png"))); // NOI18N
        btnGo.setText("GO");
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonClick(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(274, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtURL, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(291, 291, 291))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtURL, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonClick
        ScrapSaveProcess process=new ScrapSaveProcess(txtScrap);
        process.start();
    }//GEN-LAST:event_saveButtonClick

    private void scrapButtonClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scrapButtonClick
        ScrapProcess process=new ScrapProcess(txtRegEx, txtBrowser, txtScrap);
        process.start();
    }//GEN-LAST:event_scrapButtonClick

    private void matcherClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matcherClick
        MatcherProcess process = new MatcherProcess(txtBrowser,txtMatcher,txtMatcher2,txtMatcher3,txtRegEx,txtMatch);
        process.start();
    }//GEN-LAST:event_matcherClick

    private void goButtonClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonClick
        GrabberProcess process = new GrabberProcess(txtBrowser, txtURL);
        process.start();
    }//GEN-LAST:event_goButtonClick

    private void ImageButtonClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImageButtonClick
       ImageSaveProcess process=new ImageSaveProcess(txtImage);
       process.start();
    }//GEN-LAST:event_ImageButtonClick

    private void clearButtonClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonClick
       txtScrap.setText("");
    }//GEN-LAST:event_clearButtonClick

    private void matcherSaveClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matcherSaveClick
        MatcherSaveProcess process=new MatcherSaveProcess(txtMatch);
        process.start();
    }//GEN-LAST:event_matcherSaveClick

    private void matchFieldClearClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matchFieldClearClick
        txtMatch.setText("");
    }//GEN-LAST:event_matchFieldClearClick


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClearM;
    private javax.swing.JButton btnGo;
    private javax.swing.JButton btnImage;
    private javax.swing.JButton btnMatcher;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSave1;
    private javax.swing.JButton btnScrap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txtBrowser;
    private javax.swing.JTextField txtImage;
    private javax.swing.JTextArea txtMatch;
    private javax.swing.JTextField txtMatcher;
    private javax.swing.JTextField txtMatcher2;
    private javax.swing.JTextField txtMatcher3;
    private javax.swing.JTextField txtRegEx;
    private javax.swing.JTextArea txtScrap;
    private javax.swing.JTextField txtURL;
    // End of variables declaration//GEN-END:variables
}
